//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public Nullable<int> code_order { get; set; }
        public Nullable<System.DateTime> date_create { get; set; }
        public Nullable<System.TimeSpan> time_crate { get; set; }
        public Nullable<int> user_id { get; set; }
        public string status { get; set; }
        public Nullable<int> tovar_id { get; set; }
    
        public virtual Tovar Tovar { get; set; }
        public virtual Users Users { get; set; }
    }
}
